/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author jonat
 */
public class FrmDesarrollladores extends javax.swing.JFrame {

    /**
     * Creates new form FrmDecimal
     */
    public FrmDesarrollladores() {
        // Inicializa los componentes de la interfaz.
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel8.setText("Desarrolladores");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 5, 170, 30);

        jLabel11.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user.png"))); // NOI18N
        jLabel11.setText("Aleks Xavier Pineda Macias (202110060173)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(175, 70, 350, 30);

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user_female.png"))); // NOI18N
        jLabel4.setText("Andrea Gissell Castro Euceda (202110120036)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(175, 100, 360, 30);

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user_female.png"))); // NOI18N
        jLabel5.setText("Fabiana Clarisa Valladares Urbina (202010120097)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(175, 130, 380, 30);

        jLabel12.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user.png"))); // NOI18N
        jLabel12.setText("Jafeth Donatilo Rápalo Rivera (202120030040)");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(175, 160, 370, 30);

        jLabel13.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user.png"))); // NOI18N
        jLabel13.setText("Jonathan Ignacio Marley Ramirez (201920060176)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(175, 190, 380, 30);

        jLabel14.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user.png"))); // NOI18N
        jLabel14.setText("Luis Adolfo Rodriguez Lopez (201930110148)");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(175, 220, 350, 30);

        jLabel15.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user.png"))); // NOI18N
        jLabel15.setText("Miguel Ángel Díaz Mejía (202110010425)");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(175, 250, 350, 30);

        jLabel16.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user.png"))); // NOI18N
        jLabel16.setText("Milton Noel Paz Fonseca (202130060109)");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(175, 280, 350, 30);

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/cerrar.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(545, 6, 26, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/1.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 590, 35);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 35, 585, 2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/DesarrolladoresO.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(35, 140, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/3A.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         // Crea una nueva instancia de la clase FrmMenu.
        FrmMenu ingreso = new FrmMenu();
        // Muestra la ventana FrmMenu.
        ingreso.show();
        // Cierra la ventana actual o la ventana en la que se ejecuta este código.
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDesarrollladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDesarrollladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDesarrollladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDesarrollladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDesarrollladores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
