/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author jonat
 */
public class FrmOctal extends javax.swing.JFrame {

    /**
     * Creates new form FrmDecimal
     */
    public FrmOctal() {
        initComponents();
        Document doc = txtBinario.getDocument();
        ((AbstractDocument) doc).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.matches("^[01]*$")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }

    public static String binarioAOctal(String numeroBinario) {
        try {
            // Convierte el número binario en su equivalente decimal.
            int numeroDecimal = Integer.parseInt(numeroBinario, 2);
            // Convierte el número decimal en su representación octal.
            String numeroOctal = Integer.toOctalString(numeroDecimal);
            // Devuelve la cadena octal resultante.
            return numeroOctal;
        } catch (NumberFormatException e) {
            // Si ocurre una excepción de NumberFormatException (por ejemplo, si el número binario no es válido),
            // se devuelve la cadena "Error".
            return "Error";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOctal = new javax.swing.JTextField();
        btnConversion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtBinario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/cerrar.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(312, 6, 26, 25);

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        jLabel8.setText("Calculadora Binaria");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 5, 170, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 350, 35);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 35, 350, 2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/cerebroGN.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(125, 60, 100, 100);

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Conversión de Binario a Octal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(55, 170, 240, 32);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 215, 350, 2);

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese el número binario:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 238, 170, 28);

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resultado a Octal:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(115, 325, 120, 28);

        txtOctal.setEditable(false);
        txtOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOctalActionPerformed(evt);
            }
        });
        jPanel1.add(txtOctal);
        txtOctal.setBounds(30, 355, 287, 35);

        btnConversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/Conversion.png"))); // NOI18N
        btnConversion.setContentAreaFilled(false);
        btnConversion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/ConversionOver.png"))); // NOI18N
        btnConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversionActionPerformed(evt);
            }
        });
        jPanel1.add(btnConversion);
        btnConversion.setBounds(38, 412, 279, 65);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/Limpiar.png"))); // NOI18N
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/LimpiarOver.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(38, 485, 279, 65);
        jPanel1.add(txtBinario);
        txtBinario.setBounds(30, 272, 287, 35);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/3A.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 350, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        // Crea una nueva instancia de la clase FrmMenu.
        FrmMenu ingreso = new FrmMenu();
        // Muestra la ventana FrmMenu.
        ingreso.show();
        // Cierra la ventana actual o la ventana en la que se ejecuta este código.
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversionActionPerformed
        // TODO add your handling code here:
        // Obtiene el número binario ingresado en el campo de texto 'txtBinario'.
        String numeroBinario = txtBinario.getText();
        // Llama a una función llamada 'binarioAOctal' para convertir el número binario en su equivalente octal.
        String numeroOctal = binarioAOctal(numeroBinario);
        // Muestra el número octal resultante en el campo de texto 'txtOctal'.
        txtOctal.setText(numeroOctal);
    }//GEN-LAST:event_btnConversionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        // Establece el contenido del campo de texto 'txtBinario' y 'txtHexadecimal' a una cadena vacía, 
        //eliminando cualquier texto existente en él.
        txtBinario.setText("");
        txtOctal.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOctalActionPerformed
        // TODO add your handling code here:
          // Deshabilita el campo de texto 'txtOctal', lo que impide que el usuario lo edite o interactúe con él.
        txtOctal.setEnabled(false);
    }//GEN-LAST:event_txtOctalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOctal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOctal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOctal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOctal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOctal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConversion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtBinario;
    private javax.swing.JTextField txtOctal;
    // End of variables declaration//GEN-END:variables
}
